# Generated by Django 5.1.7 on 2025-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=20)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
